### ISSUE TITLE
trying to run bot.js: Error: Uncaught, unspecified "error" event. ([object Object])

### ISSUE THREAD

**Issue by DeeJayRandall** [tapsterbot/tapsterbot#2]
Running Windows 10. Running node v4.6.1. Following getting started from the README.md. When I run node src/bot.js the web server starts (and will return "Welcome to Tapster World!"). A few seconds after that I get the error below. I can't issue the go(0,0,-140) command. What am I doing wrong?

```
D:\tapsterbot-master-20170131\software>node src\bot.js
Config not specified. Loading default.
Tapster web server listening on port 8080
events.js:146
      throw err;
      ^

Error: Uncaught, unspecified "error" event. ([object Object])
    at Board.emit (events.js:144:17)
    at Board.log (D:\tapsterbot-master-20170131\software\node_modules\johnny-five\lib\board.js:630:8)
    at Board.(anonymous function) [as error] (D:\tapsterbot-master-20170131\software\node_modules\johnny-five\lib\board.js:641:14)
    at Board.<anonymous> (D:\tapsterbot-master-20170131\software\node_modules\johnny-five\lib\board.js:390:14)
    at Timer.listOnTimeout (timers.js:92:15)

D:\tapsterbot-master-20170131\software>
```

**Comment by DeeJayRandall** [comment]
Fix was to specify the COM port as COM4 in bot.js:
```
board = new five.Board({
  port: "COM4",
  debug: false
});
```

Debugging to get to that solution involved printing the arguments in board.js:
```
Board.prototype.log = function( /* type, klass, message [, long description] */ ) {
  var args = Array.from(arguments);

  console.log(args);
```

**Comment by shawnkirsch** [comment]
thanks for the fix info!
