### ISSUE TITLE
The bot.js is no longer compatible with latest version of jonny-five (v1.0.0)

### ISSUE THREAD

**Issue by huangbq4gh** [tapsterbot/tapsterbot#6]
Jonny-five have a major update/release 5 month ago. Now if you run the bot.js, it will throw error like below.

> node bot.js

> Config not specified. Loading default.
> Tapster web server listening on port 8080
> Go!
> { x: 10, y: 10, z: -150 }
> C:\GIT\GITHUB\TapsterBot\software\src\bot.js:328
>   servo1.to((angles[1]).map(config.servo1.in_min, config.servo1.in_max, config.servo1.out_min, config.servo1.out_max));
>          ^
> 
> TypeError: Cannot read property 'to' of undefined
>     at moveServosTo (C:\GIT\GITHUB\TapsterBot\software\src\bot.js:328:10)
>     at Timeout._onTimeout (C:\GIT\GITHUB\TapsterBot\software\src\bot.js:348:35)
>     at ontimeout (timers.js:486:15)
>     at tryOnTimeout (timers.js:317:5)
>     at Timer.listOnTimeout (timers.js:277:5)

**Comment by huangbq4gh** [comment]
false alarm. the solution in issue #2 solved my problem. Closing this.

**Comment by huangbq4gh** [comment]
But I think you still need to update the master branch with the "port: "COMX"" change.
